### ISSUE TITLE
Maven artifact not available in maven-central

### ISSUE THREAD

**Issue by coiouhkc** [svzdvd/jaxb-lombok-plugin#1]
Could you please deploy the artifact to Maven Central Repository?

**Comment by svzdvd** [comment]
Hi,
you can use Jitpack to use the latest snapshot:
https://jitpack.io/#svzdvd/jaxb-lombok-plugin/fff9d9a711

Add this repository to your Maven:

```	
       <repositories>
		<repository>
		    <id>jitpack.io</id>
		    <url>https://jitpack.io</url>
		</repository>
	</repositories>
```

And then the dependency:

```	
       <dependency>
	    <groupId>com.github.svzdvd</groupId>
	    <artifactId>jaxb-lombok-plugin</artifactId>
	    <version>fff9d9a711</version>
	</dependency>
```

**Comment by ergh99** [comment]
I actually had to add it as a `<pluginRepository>` to get it to resolve properly.

**Comment by coiouhkc** [comment]
Thanks for the advice, I myself recently discovered this option, unfortunately it does not work in our specific configuration, having to use nexus as proxy to the outer world without admin access to configure further proxied repositories (although jitpack.io supports nexus since 2016, if I'm not mistaken).
As as workaround I had to download and deploy the artifact to our nexus manually.
